[[redirects]]
from = '/*'
to = '/index.html'
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests; frame-src https://www.google.com; script-src 'self' 'unsafe-inline' https://maps.googleapis.com; img-src 'self' data: https://maps.googleapis.com https://maps.gstatic.com;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build]
  command = "npm run build"
  publish = "build"  # CRA build output

# Don't cache HTML (prevents stale document after deploy)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

# Long cache for hashed assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"