[[redirects]]
from = '/*'
to = '/index.html'
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests; frame-src 'self' https://www.google.com https://js.stripe.com https://*.tawk.to https://*.stripe.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com https://*.tawk.to https://*.google-analytics.com https://www.googletagmanager.com https://*.spline.design https://js.stripe.com https://m.stripe.network; img-src 'self' data: https://maps.googleapis.com https://maps.gstatic.com https://*.google-analytics.com https://www.googletagmanager.com https://*.spline.design https://asl-logos.s3.amazonaws.com https://utahabalogos.s3.us-west-1.amazonaws.com https://*.s3.amazonaws.com https://*.s3.us-west-1.amazonaws.com https://*.tawk.to https://q.stripe.com www.autismserviceslocator.com; connect-src 'self' https://*.googleapis.com https://*.googletagmanager.com https://*.google-analytics.com https://*.herokuapp.com https://*.tawk.to wss://*.tawk.to https://*.spline.design https://prod.spline.design https://api.stripe.com https://m.stripe.network; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.tawk.to; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build]
  command = "npm run build"
  publish = "build"  # CRA build output

# Don't cache HTML (prevents stale document after deploy)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

# Long cache for hashed assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"