describe('template spec', () => {
    beforeEach(() => {
      cy.visit('localhost:3000')
    })
    it('should display the main logo', () => {
      cy.get('.main-logo').should('be.visible')
    })
    it('should have a menu button', () => {
      cy.get('.menu').should('be.visible')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/"]').should('be.visible')
      cy.get('#menu-content > [href="/providers"]').should('be.visible')
      cy.get('#menu-content > [href="/screening"]').should('be.visible')
      cy.get('#menu-content > [href="/information"]').should('be.visible')
      cy.get('#menu-content > [href="/providerLogin"]').should('be.visible')
      cy.get('#menu-content > [href="/contact"]').should('be.visible')
      cy.get('#menu-content > [href="/about"]').should('be.visible')
    })
    it('should be able to navigate to the designated pages', () => {
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/"]').click()
      cy.url().should('include', '/')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/providers"]').click()
      cy.url().should('include', '/providers')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/screening"]').click()
      cy.url().should('include', '/screening')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/information"]').click()
      cy.url().should('include', '/information')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/providerLogin"]').click()
      cy.url().should('include', '/providerLogin')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/contact"]').click()
      cy.url().should('include', '/contact')
      cy.get('.menu').click()
      cy.get('#menu-content > [href="/about"]').click()
      cy.url().should('include', '/about')
    })
  })